name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - name: Read file or arbitrary multiline value into a github actions output
        id: step_one
        run: |
          {
            echo 'output_name<<ANY_DELIMITER_YOU_WANT'
            cat ../../Example.xml
          } >> "$GITHUB_OUTPUT"
